### ISSUE TITLE
Native app authentication is failing 

### ISSUE THREAD

**Issue by abidhkhan** [MicrosoftDocs/partner-center-java-docs#62]
I am trying to do native app authentication and it is failing   with the below error 

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.microsoft.aad.msal4j.Authority.getTenant(Authority.java:88)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:110)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:131)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:42)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:32)
	at com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier.execute(AcquireTokenByDeviceCodeFlowSupplier.java:23)
```

#### Code

```
 public void authenticateNativeApp(){
        IAadLoginHandler loginHandler = new AadUserLoginHandler();

        IPartnerCredentials userCredentials = PartnerCredentials.getInstance().generateByUserCredentials(
                ConfigurationHolder.getInstance().getConfiguration().getUserAuthentication().get( "ClientId" ),
                loginHandler.authenticate(),
                loginHandler );
    }
```

```
public class AadUserLoginHandler
    implements IAadLoginHandler
{
    /**
     * Logs into Azure active directory.
     * 
     * @return The authentication result.
     */
    @Override
    public AuthenticationToken authenticate()
    {
        CompletableFuture<IAuthenticationResult> future;
        Consumer<DeviceCode> deviceCodeConsumer;
        IAuthenticationResult authResult = null;
        PublicClientApplication app;
        String authority; 
        String clientId;
        String scope;

        try
        {
            authority = ConfigurationHolder
                .getInstance()
                .getConfiguration()
                .getPartnerServiceSettings()
                .get("AuthenticationAuthorityEndpoint");

            clientId = ConfigurationHolder
                .getInstance()
                .getConfiguration()
                .getUserAuthentication()
                .get("ClientId");
            
            scope = ConfigurationHolder
                .getInstance()
                .getConfiguration()
                .getUserAuthentication()
                .get("Scope");

            app = PublicClientApplication.builder(clientId)
                .authority(authority + "/common")
                .build();

            deviceCodeConsumer = (DeviceCode deviceCode) -> {
                System.out.println(deviceCode.message());
            };    
            
            future = app.acquireToken(
                DeviceCodeFlowParameters.builder(
                    Collections.singleton(scope),
                    deviceCodeConsumer)
                .build());

            future.handle((result, ex) -> {
                if(ex != null) 
                {
                    ex.printStackTrace();
                }

                return result;
            });

            authResult = future.join();

            if ( authResult == null )
            {
                throw new NullPointerException( "authentication result was null" );
            }
        }
        catch(IOException ex)
        {
            ex.printStackTrace();
        }

        return new AuthenticationToken(authResult.accessToken(), new DateTime(authResult.expiresOnDate()));
    }
}

```

**Comment by JasonWHowell** [comment]
@isaiahwilliams Can you please triage this issue. Thanks, Jason

**Comment by isaiahwilliams** [comment]
@abidhkhan thank you for opening this, if you are still encountering this issue please open a [bug](https://github.com/microsoft/Partner-Center-Java/issues/new/choose)
